name: Deploy
on: workflow_dispatch
jobs:
  runs-on: ubuntu-latest
  steps:
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build the docker image
        run: ./mvnw -ntp package -Pprod -DskipTests jib:build -Djib.to.image=sp3cialoo7/ecom-app -Djib.to.auth.username="${{secrets.DOCKER_USERNAME }}" -Djib.to.auth.password="${{secrets.DOCKER_PASSWORD }}"
