name: SSH
on: workflow_dispatch
jobs:
  build:
    name: Deploy the app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ssh to server and run commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker compose -f app.yml stop
            sudo docker rm azureuser-ecom-app-1
            sudo docker image rm sp3cialoo7/ecom-app
            sudo docker compose -f app.yml pull
            sudo docker compose -d -f app.yml up
